package com.developer.raitha_varta.viewmodel

import android.app.Activity
import android.util.Log
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import com.google.firebase.FirebaseException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.PhoneAuthCredential
import com.google.firebase.auth.PhoneAuthOptions
import com.google.firebase.auth.PhoneAuthProvider
import java.util.concurrent.TimeUnit

class AuthViewModel : ViewModel() {
    private val auth = FirebaseAuth.getInstance()

    // This ID is generated by Firebase and needed for verification
    var verificationId = mutableStateOf("")
    var isLoading = mutableStateOf(false)

    fun sendOtp(phoneNumber: String, activity: Activity, onCodeSent: () -> Unit) {
        isLoading.value = true
        val options = PhoneAuthOptions.newBuilder(auth)
            .setPhoneNumber("+91$phoneNumber") // Formatting for India
            .setTimeout(60L, TimeUnit.SECONDS)
            .setActivity(activity)
            .setCallbacks(object : PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                override fun onCodeSent(id: String, token: PhoneAuthProvider.ForceResendingToken) {
                    verificationId.value = id
                    isLoading.value = false
                    onCodeSent()
                }

                override fun onVerificationCompleted(credential: PhoneAuthCredential) {
                    isLoading.value = false
                }

                override fun onVerificationFailed(e: FirebaseException) {
                    isLoading.value = false
                    Log.e("AuthError", "SMS Failed: ${e.message}")
                }
            }).build()
        PhoneAuthProvider.verifyPhoneNumber(options)
    }
}